app/home/__init__.py
#coding: utf8
from flask import Blueprint


# 定义蓝图
home = Blueprint("home", __name__)


import app.home.views

app/home/views.py
#coding=utf-8


from . import home
from flask import render_template, redirect, url_for, session, request, flash, jsonify
from functools import wraps
from app import getConn


def home_login_req(f):
    """
    访问控制装饰器
    """
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'account' not in session:
            return redirect(url_for('home.login', next=request.url))
        return f(*args, **kwargs)
    return decorated_function


@home.route('/')
def index():
    # 渲染并返回 home/index.html 页面
    return render_template('home/index.html')


@home.route('/login/', methods=['GET', 'POST'])
def login():
    """
    用户登录
    """
    if request.method == 'POST':
        account = request.form['account']
        password = request.form['password']
        db = getConn()
        cursor = db.cursor()
        sql = 'select id, account, password, username from user where account="%s"' %account
        try:
            cursor.execute(sql)
        except:
            err_msg = u'服务器内部错误，登录失败，请重新登录'
        else:
            value = cursor.fetchone()
            if not value:  # 判断用户是否存在
                err_msg = u'账号不存在'
            else:
                columns = ('id', 'account', 'password', 'username')
                user = dict(zip(columns, value))
                if user['password'] == password:  # 判断密码是否正确
                    del user['password']
                    for key in user:
                        session[key] = user[key]
                    err_msg = ''
                else:
                    err_msg = u'密码错误'
        db.close()
        return jsonify({'err_msg': err_msg})
    else:
        return render_template('home/login.html')
 

@home.route('/logout/')
@home_login_req
def logout():
    """
    退出
    """
    columns = ('id', 'account', 'password', 'username')
    for column in columns:
        session.pop(column, None)
    return redirect(url_for('home.login'))


@home.route('/user/', methods=['GET', 'POST'])
@home_login_req
def user():
    if request.method == 'POST':
        """
        对数据进行验证
        对数据进行验证
        对数据进行验证
        对数据进行验证
        对数据进行验证
        """
        user_id = request.form['user_id']
        telephone = request.form['telephone']
        qq = request.form['qq']
        db = getConn()
        cursor = db.cursor()
        sql = 'update user set telephone="%s", qq="%s" where id="%s"' %(telephone, qq, user_id)
        try:
            cursor.execute(sql)
            db.commit()
        except:
            db.rollback()
            err_msg = u'服务器内部错误，保存个人信息失败，请重试'
        else:
            err_msg = ''
        db.close()
        return jsonify({'err_msg': err_msg})
    else:
        account = session['account']
        db = getConn()
        cursor = db.cursor()
        sql = '''select id, account, username, education, grade, score, fund, telephone, qq from user
                 where account="%s"''' %account
        try:
            cursor.execute(sql)
        except:
            user = None
        else:
            user = cursor.fetchone()
            columns = ('id', 'account', 'username', 'education', 'grade', 'score', 'fund', 'telephone', 'qq')
            user = dict(zip(columns, user))
        db.close()
        return render_template('home/user.html', user=user)  


@home.route('/pwd/', methods=['GET', 'POST'])
@home_login_req
def pwd_edit():
    """
    修改密码
    """
    """
    对输入的字段进行验证
    对输入的字段进行验证
    对输入的字段进行验证
    对输入的字段进行验证
    """
    if request.method == 'POST':
        old_password = request.form['old_password']
        new_password = request.form['new_password']
        db = getConn()
        cursor = db.cursor()
        sql = 'select password from user where id=%s'%(session['id'])
        try:
            cursor.execute(sql)
        except:
            err_msg = u'服务器内部错误，修改密码失败，请重试'
        else:
            password = cursor.fetchone()[0]
            if password != old_password:
                err_msg = u'旧密码错误'
            else:
                sql = 'update user set password="%s" where id="%s"'%(new_password, session['id'])
                try:
                    cursor.execute(sql)
                    db.commit()
                except:
                    db.rollback()
                    err_msg = u'服务器内部错误，修改密码失败，请重试'
                else:
                    err_msg = ''
        db.close()
        return jsonify({'err_msg': err_msg})
    else:
        return render_template('home/pwd.html')


@home.route('/score/')
@home_login_req
def score():
    """
    得分记录页面
    """
    db = getConn()
    cursor = db.cursor()
    sql = '''select value, summary, detail, update_time from scorelog
             where user_id="%s" 
             order by update_time DESC''' %session['id']
    try:
        cursor.execute(sql)
    except:
        pass
    else:
        logs = []
        columns = ('value', 'summary', 'detail', 'update_time')
        for item in cursor.fetchall():
            logs.append(dict(zip(columns, item)))
    db.close()
    return render_template('home/score.html', logs = logs)


@home.route('/fund/')
@home_login_req
def fund():
    """
    额度记录页面
    """
    db = getConn()
    cursor = db.cursor()
    sql = '''select value, summary, detail, update_time from fundlog
             where user_id="%s" 
             order by update_time DESC''' %session['id']
    try:
        cursor.execute(sql)
    except:
        pass
    else:
        logs = []
        columns = ('value', 'summary', 'detail', 'update_time')
        for item in cursor.fetchall():
            logs.append(dict(zip(columns, item)))
    db.close()
    return render_template('home/fund.html', logs = logs)


@home.route('/score/<int:id>')
@home_login_req
def admin_score(id=None):
    """
    得分记录页面
    """
    db = getConn()
    cursor = db.cursor()
    sql = '''select value, summary, detail, update_time from scorelog
             where user_id="%s" 
             order by update_time DESC''' %id
    try:
        cursor.execute(sql)
    except:
        pass
    else:
        logs = []
        columns = ('value', 'summary', 'detail', 'update_time')
        for item in cursor.fetchall():
            logs.append(dict(zip(columns, item)))
    db.close()
    return render_template('home/score.html', logs = logs)


@home.route('/fund/<int:id>')
@home_login_req
def admin_fund(id=None):
    """
    额度记录页面
    """
    db = getConn()
    cursor = db.cursor()
    sql = '''select value, summary, detail, update_time from fundlog
             where user_id="%s" 
             order by update_time DESC''' %id
    try:
        cursor.execute(sql)
    except:
        pass
    else:
        logs = []
        columns = ('value', 'summary', 'detail', 'update_time')
        for item in cursor.fetchall():
            logs.append(dict(zip(columns, item)))
    db.close()
    return render_template('home/fund.html', logs = logs)

app/templates/home/alert.html
<div id="my-alert" class="alert alert-danger" style="display:none">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong>失败！</strong><span></span>
</div>

app/templates/home/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>CAS 考评系统</title>
    <!-- IE8/9 及以后的版本都会以最高版本IE来渲染页面 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- 包含头部信息用于适应不同设备 -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 包含 bootstrap 样式表 -->
    <link rel="stylesheet" href="https://apps.bdimg.com/libs/bootstrap/3.2.0/css/bootstrap.min.css">
    <!-- 网站 logo -->
    <link rel="icon" href="{{ url_for('static', filename='home/images/favicon.ico') }}">
    
    <!-- HTML5 Shiv 和 Respond.js 用于让 IE9 以下版本支持HTML5元素和媒体查询 -->
    <!-- 必须放在 <head> 元素中，因为 IE 浏览器在解析 HTML5 新元素时需要先加载该文件 -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <!-- 自定义样式表 -->
    {% block css %}
        <link rel="stylesheet" href="{{ url_for('static', filename='home/css/base.css') }}">
    {% endblock %}
</head>

<body>
    {% block content %}
    {% endblock %}
    <!-- JavaScript 放置在文档最后面可以使页面加载速度更快 -->
    <!-- 可选: 包含 jQuery 库 -->
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <!-- 可选: 合并了 Bootstrap JavaScript 插件 -->
    <script src="https://apps.bdimg.com/libs/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    {% block js %}
    {% endblock %}
</body>

</html>

app/templates/home/fund.html
{% extends "home/base.html" %}
{% block content %}
<div class="container">
    {% include "home/nav.html" %}
    <div class="row clearfix">
        <div class="col-md-12 column">
        <h3>额度奖励/扣除记录</h3>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-12 column">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>额度</th>
                        <th>标签</th>
                        <th>详细说明</th>
                        <th>时间</th>
                    </tr>
                </thead>
                <tbody>
                    {% for log in logs %}
                        {% if log.value < 0 %}
                            <tr class="danger">
                                <td>{{ log.value }}</td>
                                <td>{{ log.summary }}</td>
                                <td>{{ log.detail }}</td>
                                <td>{{ log.update_time }}</td>
                            </tr>
                        {% else %}
                            <tr class="success">
                                <td>{{ log.value }}</td>
                                <td>{{ log.summary }}</td>
                                <td>{{ log.detail }}</td>
                                <td>{{ log.update_time }}</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                    <ul class="pagination">
                        <li>
                            <a href="#">Prev</a>
                        </li>
                        <li>
                            <a href="#">1</a>
                        </li>
                        <li>
                            <a href="#">2</a>
                        </li>
                        <li>
                            <a href="#">3</a>
                        </li>
                        <li>
                            <a href="#">4</a>
                        </li>
                        <li>
                            <a href="#">5</a>
                        </li>
                        <li>
                            <a href="#">Next</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    $(function(){
        $("nav li:nth-child(3)").addClass("active");
        $("td:empty").text('---');
    });
</script>
{% endblock %}

app/templates/home/index.html
<!-- 继承夫模板 base.html -->
{% extends "home/base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='home/css/index.css') }}">
{% endblock %}

{% block content %}
<header>
    <div class="container">
        <nav class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">CAS</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('home.login') }}">登录</a>
                    </li>
                    <li>
                        <a href="#">退出</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>
<main role="main">
    <section>
        <div class="container">
            <div class="jumbotron">
                <h1>
                    Welcome!
                </h1>
                <p>
                    欢迎登录中国科学院大学信息工程研究所第五研究室 CAS 组在线考评系统！
                </p>
                <p>
                    <a class="btn btn-primary btn-large" href="http://www.iie.ac.cn/">iie - cas</a>
                </p>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <!-- 行（row）必须包含在 .container 或者 .container-fluid 中 -->
            <div class="row">
                <!-- 只有列（column）可以作为行的直接子元素 -->
                <div class="col-md-4">
                    <div class="thumbnail">
                        <img alt="300x200" src="{{ url_for('static', filename='home/images/github.png') }}" />
                        <div class="caption">
                            <h3>
                                GitHub
                            </h3>
                            <p>
                                这里有我们 CAS 小组的的学习、工作成果，欢迎大家访问！
                            </p>
                            <p>
                                <a class="btn btn-primary" href="https://github.com/iie-cas">Go</a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="thumbnail">
                        <img alt="300x200" src="{{ url_for('static', filename='home/images/cste.png') }}" />
                        <div class="caption">
                            <h3>
                                CSTE
                            </h3>
                            <p>
                                这是一个集成了 QEMU 和许多漏洞实例的框架，可以用来验证各种防御机制的能力。欢迎使用！
                            </p>
                            <p>
                                <a class="btn btn-primary" href="https://github.com/iie-cas/CSTE1.0">Go</a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="thumbnail">
                        <img alt="300x200" src="{{ url_for('static', filename='home/images/sr.png') }}" />
                        <div class="caption">
                            <h3>
                                科研在线
                            </h3>
                            <p>
                                这是我们使用的团队管理工具！这是我们使用的团队管理工具！这是我们使用的团队管理工具！
                            </p>
                            <p>
                                <a class="btn btn-primary" href="https://passport.escience.cn/login">Go</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
<footer class="text-muted">
    <div class="container">
        <p class="float-left">CAS 考评系统 @iie-cas</p>
    </div>
</footer>
{% endblock %}

app/templates/home/login.html
{% extends "home/base.html" %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='home/css/signin.css') }}">
{% endblock %}

{% block content %}
<div class="container">
  <form class="form-signin">
    <h2 class="form-signin-heading">Please sign in</h2>
    {% include "home/alert.html" %}
    <input type="text" id="account" class="form-control" placeholder="用户名" required autofocus>
    <input type="password" id="password" class="form-control" placeholder="密码" required>
    <div class="checkbox">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
  </form>
</div>
{% endblock %}

{% block js %}
<script src=" {{ url_for('static', filename='home/js/my.js') }} "></script>

<script>

  $("button").click(function() {
    hideMyAlert();
    var account = $("#account").val();
    var password = $("#password").val();
    if(!validAccount(account)) {
      showMyAlert("账号不合法，账号只包含字母和数字，长度在 3-20 之间");
      return false;
    }
    if(!validAccount(password)) {
      showMyAlert("密码不合法，密码只包含字母和数字，长度在 6-20 之间");
      return false;
    }
    $.ajax({
      type: "POST",
      async: true,
      url: "{{ url_for('home.login') }}",
      dataType: "json",
      data: {
        "account": account,
        "password": password
      },
      success: function(data, textStatus) {
        if(data.err_msg !== "") {
          showMyAlert(data.err_msg);
        } else {
          window.location.href ="{{ url_for('home.user') }}";
        }
      }
    });
    return false;
  });

</script>
{% endblock %}

app/templates/home/nav.html
<div class="row clearfix">
    <div class="col-md-12 column">
        <nav class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('home.index') }}">CAS</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{{ url_for('home.user') }}">个人信息</a>
                    </li>
                    <li>
                        <a href="{{ url_for('home.score') }}">分数</a>
                    </li>
                    <li>
                        <a href="{{ url_for('home.fund') }}">金额</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('home.logout') }}">退出</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>

app/templates/home/pwd.html
{% extends "home/base.html" %}

{% block content %}
<div class="container">
    {% include "home/nav.html" %}
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h3>修改密码</h3>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form role="form">
                <fieldset>
                    {% include "home/alert.html" %}
                    <div class="form-group">
                        <label><span class="glyphicon glyphicon-lock"></span>&nbsp;旧密码</label>
                        <input id="old-password" class="form-control" placeholder="旧密码" type="password" autofocus>
                    </div>
                    <div class="form-group">
                        <label><span class="glyphicon glyphicon-lock"></span>&nbsp;新密码</label>
                        <input id="new-password" class="form-control" placeholder="新密码" type="password">
                    </div>
                    <div class="form-group">
                        <label><span class="glyphicon glyphicon-lock"></span>&nbsp;确认密码</label>
                        <input id="valid-password" class="form-control" placeholder="确认密码" type="password">
                    </div>
                    <button class="btn btn-success"><span class="glyphicon glyphicon-edit"></span>&nbsp;保存修改</button>
                </fieldset>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src=" {{ url_for('static', filename='home/js/my.js') }} "></script>

<script>

    $(function(){
        $("nav ul:nth-child(1) li:nth-child(1)").addClass("active");
    });

    $("button").click(function() {
        hideMyAlert();
        var old_password = $("#old-password").val();
        var new_password = $("#new-password").val();
        var valid_password = $("#valid-password").val();
        if(!validPassword(old_password)) {
            showMyAlert("输入的旧密码不合法，密码只包含字母和数字，长度在 6-20 之间");
            return false;
        }
        if(!validPassword(new_password)) {
            showMyAlert("输入的新密码不合法，密码只包含字母和数字，长度在 6-20 之间");
            return false;
        }
        if(new_password !== valid_password) {
            showMyAlert("两次输入的密码不一致");
            return false;        
        }
        $.ajax({
            type: "POST",
            async: true,
            url: "{{ url_for('home.pwd_edit') }}",
            dataType: "json",
            data: {
                "old_password": old_password,
                "new_password": new_password
            },
            success: function(data, textStatus) {
                if(data.err_msg !== "") {
                    showMyAlert(data.err_msg);
                } else {
                    showSuccess("修改密码成功，请重新登录");
                    setTimeout(function() {
                        window.location.href = "{{ url_for('home.logout') }}";
                    }, 1000);
                }
            }
        });
        return false;
      });

</script>
{% endblock %}

app/templates/home/score.html
{% extends "home/base.html" %}
{% block content %}
<div class="container">
    {% include "home/nav.html" %}
    <div class="row clearfix">
        <div class="col-md-12 column">
        <h3>加/减分记录</h3>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-12 column">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>分值</th>
                        <th>标签</th>
                        <th>详细原因</th>
                        <th>时间</th>
                    </tr>
                </thead>
                <tbody>
                    {% for log in logs %}
                        {% if log.value < 0 %}
                            <tr class="danger">
                                <td>{{ log.value }}</td>
                                <td>{{ log.summary }}</td>
                                <td>{{ log.detail }}</td>
                                <td>{{ log.update_time }}</td>
                            </tr>
                        {% else %}
                            <tr class="success">
                                <td>{{ log.value }}</td>
                                <td>{{ log.summary }}</td>
                                <td>{{ log.detail }}</td>
                                <td>{{ log.update_time }}</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                    <ul class="pagination">
                        <li>
                            <a href="#">Prev</a>
                        </li>
                        <li>
                            <a href="#">1</a>
                        </li>
                        <li>
                            <a href="#">2</a>
                        </li>
                        <li>
                            <a href="#">3</a>
                        </li>
                        <li>
                            <a href="#">4</a>
                        </li>
                        <li>
                            <a href="#">5</a>
                        </li>
                        <li>
                            <a href="#">Next</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    $(function(){
        $("nav li:nth-child(2)").addClass("active");
        $("td:empty").text("---");
    });
</script>
{% endblock %}

app/templates/home/user.html
{% extends "home/base.html" %}

{% block content %}
<div class="container">
    {% include "home/nav.html" %}
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h3>个人信息页</h3>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form role="form">
                <fieldset>
                    {% include "home/alert.html" %}
                    <input type="hidden" id="userid" value="{{ user.id }}">
                    <div class="form-group">
                        <label>分数</label>
                        <input id="score" class="form-control" type="text" readonly unselectable="on" value="{{user.score}}">
                    </div>
                    <div class="form-group">
                        <label>额度</label>
                        <input id="fund" class="form-control"  type="text" readonly unselectable="on" value="{{user.fund}}">
                    </div>
                    <div class="form-group">
                        <label>姓名</label>
                        <input id="username" class="form-control"  type="text" readonly unselectable="on" value="{{user.username}}">
                    </div>
                    <div class="form-group">
                        <label>学历</label>
                        <input id="education" class="form-control" type="text" readonly unselectable="on" value="{{user.education}}">
                    </div>
                    <div class="form-group">
                        <label>年级</label>
                        <input id="grade" class="form-control" type="text" readonly unselectable="on" value="{{user.grade}}">
                    </div>
                    <div class="form-group">
                        <label>手机</label>
                        <input id="telephone" class="form-control" type="text" value="{{ user.telephone }}">
                    </div>
                    <div class="form-group">
                        <label>QQ</label>
                        <input id="qq" class="form-control" name="qq" type="text" value="{{ user.qq }}">
                    </div>
                    <a id="save-edit" class="btn btn-success"><span class="glyphicon glyphicon-saved"></span>&nbsp;保存修改</a>
                    <a id="edit-password" href="{{ url_for('home.pwd_edit') }}" class="btn btn-danger"><span class="glyphicon glyphicon-edit"></span>&nbsp;修改密码</a>
                </fieldset>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src=" {{ url_for('static', filename='home/js/my.js') }} "></script>
<script>
    
    $(function(){
        $("nav ul:nth-child(1) li:nth-child(1)").addClass("active");
        $("input:empty").attr({
            "placeholder": "请及时录入"
        });
    });

    $("#save-edit").click(function() {
        hideMyAlert();
        var user_id = $("#userid").val();
        var telephone = $("#telephone").val();
        var qq = $("#qq").val();
        if(!validTelephone(telephone)) {
            showMyAlert("手机号码格式不正确，手机号码长度为 11 位，第一位必须为 1，第二位可为 3、4、5、7、8");
            return false;
        }
        if(!validQQ(qq)) {
            showMyAlert("输入的 QQ 号格式不正确，QQ 号码长度为 5-11 且首位不能为 0");
            return false;
        }
        $.ajax({
            async: true,
            type: "POST",
            url: "{{ url_for('home.user') }}",
            dataType: "json",
            data: {
                "user_id": user_id,
                "telephone": telephone,
                "qq": qq
            },
            success: function(data, textStatus) {
                if(data.err_msg !== "") {
                    showMyAlert(data.err_msg);
                }
                else {
                    showSuccess("保存个人信息成功");
                }
            }
        });
        return false;
    });

</script>
{% endblock %}